site_name: Xamarin Forms Guide
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
markdown_extensions:
  - codehilite
  - admonition  
  - meta



copyright: 'Copyright &copy; 2018 - Peruzal'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/peruzal'
    - type: 'twitter'
      link: 'https://twitter.com/peruzal'
        
pages:
  - Home: index.md
  - Introduction to Xamarin Forms: introduction.md
  - XAML:
    - Introduction to XAML: xaml/introduction.md
    - Platform Specifics: xaml/on-platform.md
    - XAML Mark Extension: xaml/xaml-markup-extensions.md
  - Xamarin Forms Views: 
      - Label: views/label.md
      - Entry: views/entry.md
      - Button: views/buttons.md
      - Editor: views/editor.md
      - Image: views/image.md
      - Switch: views/switch.md
      - Stepper: views/stepper.md
      - Picker: views/picker.md
      - Date Picker: views/date-picker.md
      - Time Picker: views/time-picker.md
      - Slider: views/slider.md
      - Activity Indicator: views/activity-indicator.md
      - ProgressBar: views/progress-bar.md
      - Search Bar: views/search-bar.md
      - List View: views/list-view.md
      - Map: views/map.md
      - Carousel View: views/carousel-view.md
      - Web View: views/web-view.md
  - Layouts:
      - Layout Options: layouts/layout-options.md
      - Stack Layout: layouts/stack-layout.md
      - Grid Layout: layouts/grid-layout.md
      - Absolute Layout: layouts/absolute-layout.md
      - Relative Layout: layouts/relative-layout.md
      - Flex Layout: layouts/flex-layout.md
      - Scroll View: layouts/scroll-view.md
  - Navigation: 
    - Hierachical Navigation: navigation/hierachical-navigation.md
    - Tabbed Navigation: navigation/tabbed-navigation.md
    - Master Detail Navigation: navigation/master-detail-navigation.md
    - Swipe Navigation: navigation/carousel.md
    - Displaying Popups:
      - Normal Popups: navigation/pop-ups/pop-ups.md
      - Modal Popups: navigation/pop-ups/modal-pop-ups.md
  
  - Customizing ListView: customizing-listview.md
  - Styles and Resources: ui-styles.md
  - Networking: networking.md
  - Persistance and SQLite: 
      - Preferences: persistence/preferences.md
      - SQLite.NET: persistence/sqlite.md
  - Data Binding: data-binding.md
  - Model View-View Model(MVVM): mvvm.md
  - Dependency Injection: dependency-injection.md
  - Extending Controls with Behaviours: behaviours.md
  - Xamarin.Essentials Cross Platform API: xamarin-essentials.md
